### ISSUE TITLE
Some notes on code style and implementation details

### ISSUE THREAD

**Issue by ilyahumbar** [AGS17/iTechTest#1]
### Slider block implementation issues
- [x] Slider navigation should be implemented as a separate block. And I think it should include titles (`slider__list-item-description`), navigation buttons, and background. You can use `slider__nav` element to add transparency to that block.
- [x] Implementation of `slider__list-item-description` is rather hacky. [This screenshot](https://www.screencast.com/t/2G26RYyT) clearly shows what i mean. WHy don't you use `position: absolute` with `bottom: 0`? It's simple and expressive. You will need just to set height. More over, navigation arrows are positioned separately using different set of hacks...
- [x] remove empty `slider__item` elements or at least fix them: 1. they should be named  `slider__list-item` and they should have `dispaly: none` set in styles if they are not shown

### `container` pseudo block
- [x] I understand it's purpose (it's just a simple wrapper for positioning child elements), but it doesn't play well with BEM. I would do it the following way: 
1. You introduce `page-section` block that contains some basic markup  (e.g. padding which can be consistent across all sections, I don't see much reason use different numbers for demo purposes) and you use this block for each `section` in your page.
2. You also introduce `page-section__content` element (formerly `container`) which limits width of content.

### Random
- [x] `text_type_quote`, `heading_type_subheading`, `heading_color_negative`, `heading_align_center`, `post_type_twitter` are named not by BEM.
- [x] `info-card__icon` element styles should be devided into block (icon inside circle) and element (positioning inside `info-card` block. You can leave `info-card__icon` name for this element)
- [x] Shouldn't `search-form__button` also be a button? Whole `search-form` block can be rewritten to be more reusable (e.g color chema should be applied only inside search-section. But if we would like to use it in other places, would probably use different colors).
- [x] `updates__blog`, `updates__twitter`, `updates__contact` should also be separate blocks so they can be reusable.

**Comment by AGS17** [comment]
### Slider block implementation issues
1. Don't understand why navigation block should include titles... I think it depends on current slide and it will be simple to animate slide switching with title together. Am I wrong?
2. Fixed
3. Fixed
### `container` pseudo block
So, I did padding exactly as it was on design layout - Fixed
### Random
1. Why? It's [modifiers](http://en.bem.info/methodology/quick-start/#key-value)...
2. Fixed
3. Fixed
4. I think about it, but I decided that they are not needed. Because no additional styles needed and theirs classes will be empty. Anyway, Fixed.
